### ISSUE TITLE
change in communicating locks

### ISSUE THREAD

**Issue by vlimant** [SmartDataProjects/dynamo#251]
mostly to keep things tracked, https://github.com/CMSCompOps/WmAgentScripts/pull/341 
there's going to be a couple of things to change and check that we can put in this issue

**Comment by vlimant** [comment]
Now that I understand a bit better the api 

/registry/applock/lock?service=unified&app=detox

 I think you do not even need to read in the lockoflock DB in unified.

Indeed, that api will return “wait” if unified should not be going, and dynamo should not go once that call returned “ok”.
That api and lockoflock are 100% redundant it seems.

Can you please confirm, get rid of the access, and I'll remove it on unfied's end.

**Comment by maierbenedikt** [comment]
Still testing ... in principle what you say is correct though. There might be the possibility though for exactly such a deadlock as you mention. It may be however that we have to keep the lockoflock until next week.

**Comment by vlimant** [comment]
I think we finalized this
